### ISSUE TITLE
Cache example not working

### ISSUE THREAD

**Issue by mdorier** [haampie-spack/setup-spack#6]
The example that caches the installed packages does not work:

- When using spack@develop, the spack.lock file contains a commit field in the spack section that is very likely to be different between two runs given how frequently new commits land in spack.
- When using a fixed ref (e.g. v0.20.0), the commit is the same, but the spack.lock file may still look different between two runs because packages may appear in different order.
- `jq --sort-keys` can be used to sort the `concrete_specs` section, but does not sort the `roots` section, which is an array.

Is there a spack command that could generate a hash that remains the same even when updating the develop branch (as long as packages themselves are not updated)?

**Comment by mdorier** [comment]
I figured out that this command can generate a file that is resilient to changes in spack commits and non-deterministic json ordering of fields:

```
jq --sort-keys 'del(.spack.commit) | del(.roots)' tests/spack.lock > key.json
```

(in this case my environment file is `tests/spack.yaml`, which produces `tests/spack.lock` when concretized).

You can then give the `key.json` file as follows to the cache actions:

```
- name: Restore Spack cache
  uses: actions/cache@v2
  with:
    path: ~/.spack-ci
    key: spack-${{ hashFiles('key.json') }}
```

Feel free to add this solution to your README if you find it satisfactory.

**Comment by haampie** [comment]
Caching can now be done on top of Github Packages, see https://github.com/spack/github-actions-buildcache
